#!/usr/bin/python3

import sys
import os
import mimetypes
import urllib
from mdreader import mdreader
from mediabase import mediabase

def scan_file (path):
	url = 'file://'+urllib.parse.quote(path)
	if path.endswith('.mpc') or path.endswith('.ape'):
		type='audio'
	else:
		(type, enc) = mimetypes.guess_type(url)
	if not type:
		return None
	if not type.startswith('audio'):
		return None
	if type.endswith('x-mpegurl'):
		return None
	return mreader.read_metadata(url)

if __name__ == '__main__':
	mreader = mdreader()
	mbase = mediabase('chirpy.sqlite')
	mimetypes.init()
	for cdir, dirs, files in os.walk(sys.argv[1]):
		for f in files:
			path = os.path.join(cdir,f)
			ctime = os.stat(path).st_ctime
			(song_id, basetime) = mbase.getCTime(path)
			if basetime < ctime:
				mobject = scan_file(path)
				if mobject:
					mobject['ctime'] = [ctime]
					mobject['path'] = [path]
					mobject['song_id'] = song_id
					mbase.addObj(mobject)		
	mbase.deleteUnreferenced("artists","song_artists","artist_id")
	mbase.deleteUnreferenced("genres","song_genres","genre_id")
	mbase.deleteUnreferenced("albums","songs","album")
	mbase.deleteUnreferenced("categories","albums","category")
